### PR TITLE
Allow moment

### PR DESCRIPTION
**Pull request by princemaple**
:koala: 

/cc @zendesk/quokka

### CODE REVIEW

**Comment by sandlerr** [comment]
+1

**Comment by danielbreves** [comment]
?

**Comment by svizzari** [comment]
:+1:

**Comment by princemaple** [comment]
Public: we now have access to moment js in Zendesk agent interface, so apps can use moment.js without including it as an extra file.

**Comment by ocke** [comment]
:+1: Great news guys. We use it all the time and now we can remove it from our apps lib dir.

**Pull request merged**
