### PR TITLE
[LOCAL-44] Strings: reverse sweep (auto)

### PR DESCRIPTION
**Pull request by string-sweep**
/cc @zendesk/i18n @zendesk/i18n-dev

### Risks
Low. English edits and title improvements.

### CODE REVIEW

**Comment by mariasica** [comment]
👍 on green

**Comment by dadah89** [comment]
@seangoedecke could you restart the build please and see if we get it green?

**Comment by seangoedecke** [comment]
Hi @dadah89, this wasn't a flaky test. There's a spec that checks that `en.yml` matches the translations in `zendesk_apps_support.yml`(you can run a rake task `i18n:standardize`) to sync `en.yml` up. I've done it and pushed a commit, so the test should turn green.

**Comment by svizzari** [comment]
Thanks @seangoedecke, I was just about to do the same 👏

**Comment by seangoedecke** [comment]
Aaand the test is still red. Looks like the rake task pulled in some other unmerged changes from `en.yml` (how'd they get to master???) and broke some tests which were expecting certain error messages. @fvzzy I remember you were working on the svg stuff in ZAS - do you know where these error messages come from? If they're in master we can probably just merge/rebase this PR.

**Comment by dadah89** [comment]
Tks!

@seangoedecke @svizzari @fvzzy with that test (or other similar ones), we'll need your team to fix those reverse sweep PRs tests and have it merged before the subsequent Tuesday (when we do the next string sweep) to avoid conflicts in Rosetta. If your team is ok with that then no worries, otherwise you might want to think of a different way of testing strings that allow reverse sweep PRs to be merged without needing extra changes (maybe relax the tests? have a pre-commit hook check instead?). Feel free to ping us with any questions!

**Pull request merged**
