### PR TITLE
Added backwards comp. test and fixed functionality

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description

Added backwards comp. test and fixed functionality

### References
* JIRA: 

### Risks

### CODE REVIEW

**Comment by sandlerr** [comment]
do we actually have any apps that are defined like this?

**Comment by danielbreves** [comment]
We shouldn't have.

**Comment by ocke** [comment]
Yes we do, there were apps in tests of ZAF made with this.

**Comment by danielbreves** [comment]
@ocke what do you mean by "apps in tests of ZAF"? If we wrote test apps in this format we should simply update them.

**Pull request closed without merging**
