### PR TITLE
Change zopim to chat

### PR DESCRIPTION
**Pull request by xuebingli**
:bear:

/cc @zendesk/wombat @zendesk/vegemite 

### Description
Change `zopim` to `chat`, as suggested by @timbertson https://github.com/zendesk/zendesk_app_market/pull/1720#discussion_r61212533

### Risks
* None

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by timbertson** [comment]
Does `zopim` appear in any existing `manifest.json`s? i.e. do we need to support `zopim` still for backwards compatability?

**Comment by xuebingli** [comment]
@timbertson nope. `Product` is not currently in use.

**Comment by timbertson** [comment]
:+1:

**Comment by danielbreves** [comment]
@timbertson [Zopim KB app](https://github.com/zopim/knowledgebase_app/blob/master/zendesk_app/manifest.json#L11-L13) references `zopim` as a location. Are we mapping locations to products anywhere?

**Pull request merged**
