### PR TITLE
[LOCAL-44] Strings: reverse sweep (auto)

### PR DESCRIPTION
**Pull request by string-sweep**
/cc @zendesk/i18n @zendesk/i18n-dev

### Risks
Low. English edits and title improvements.

### CODE REVIEW

**Comment by mariasica** [comment]
on green 👍

**Comment by damiann** [comment]
@zendesk/vegemite can someone restart the failing test? I've no permissions. Thanks!

**Comment by dadah89** [comment]
Tks @seangoedecke !

**Pull request merged**
