### PR TITLE
Add name to manifest

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description
Make name a thing

### References
* JIRA: 

### Risks
- [high] roman unpleased

### CODE REVIEW

**Comment by sandlerr** [comment]
won't this cause confusion though because it is only used under zat?

**Comment by ocke** [comment]
@sandlerr I added a comment to say it's only used in ZAT. Currently. Because I would like to change that.

**Comment by sandlerr** [comment]
a comment is good, but most people don't look at the code, they only run it. What about emitting a warning on the console?

**Comment by sandlerr** [comment]
^ as a separate PR is fine

**Comment by ocke** [comment]
I added a message here: https://github.com/zendesk/zendesk_apps_tools/pull/158

**Pull request merged**
