### PR TITLE
Add location for editor apps

### PR DESCRIPTION
**Pull request by roseleaf**
cc @zendesk/wombat @zendesk/orchid 

Once we get https://github.com/zendesk/zendesk_console/pull/12267 merged back into lotus, we will want to be able to indicate the 'ticket_editor' location to test out the new editor app location.

Wombats: can we redeploy ZAS once this is reviewed?

### CODE REVIEW

**Comment by xuebingli** [comment]
@zendesk/wombat The code looks good to me. 

We'll need to make sure this new location does not appear in apps reordering page.

**Comment by roseleaf** [comment]
@xuebingli what do we need to do to make sure it's ready?

**Comment by fbvilela** [comment]
Hi @roseleaf, do you really need to make this location orderable? 

It does break the manage page - reorder functionality as Xuebing pointed out.

https://cl.ly/122b2m3l1u2G/Screen%20Shot%202016-10-25%20at%204.26.41%20PM.png

**Comment by sandlerr** [comment]
wouldn't the fix be to just add a string?

**Comment by fbvilela** [comment]
not only that... we also fetch a template for each orderable location
adding the translation string results in:

**Comment by sandlerr** [comment]
Seems reasonable to deploy this non-orderable and make it orderable once the translations and assets are in place?

**Comment by fbvilela** [comment]
They could deploy this non-orderable and all we have to do is BUMP ZAS and deploy.

                     ... OR

To make this orderable we need to( in ZAM ): 

1 - add translation string like https://github.com/zendesk/zendesk_app_market/blob/master/config/locales/translations/apps_en.yml#L2261

2 -  add the appropriate asset like these ones: https://github.com/zendesk/zendesk_app_market/tree/master/app/assets/javascripts/templates/locations

3 - use the template in: https://github.com/zendesk/zendesk_app_market/blob/master/app/assets/javascripts/app_market/directives.module.js#L220

**Comment by sandlerr** [comment]
Doesn't seem like something that should be part of the scope of a team that's just trying to implement an app location, vegemite and wombat should take that on. I created https://zendesk.atlassian.net/browse/APPS-3242 to do those tasks, let's ship this non-orderable for now.

**Comment by roseleaf** [comment]
That's fine. 💇  how about now?

**Comment by xuebingli** [comment]
👍  LGTM

**Pull request merged**
